List & Detail Payments Endpoint
panicua/library-service pull request #9
Opened 2024-06-14 11:16 UTC by messedxup

2024-06-14 12:08 UTC, panicua requested changes
models:
Add min price as decimal 0.00.
change session_url to Urlfield
change session_id to Integerfield

2024-06-15 07:59 UTC, nicksetrakov requested changes

2024-06-15 07:59 UTC, nicksetrakov commented on payment_app/models.py
> +    borrowing = models.ForeignKey(
I think, that One borrowing can take only One Payment, so OneToOneField

2024-06-15 22:28 UTC, nicksetrakov approved these changes
gj

2024-06-16 01:51 UTC, panicua approved these changes

2024-06-16 01:52 UTC, merged